[package]
name = "zmqtest"
version = "0.1.0"
authors = ["Salim Alam <salam@chef.io>"]

[dependencies]
rand = "*"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"
